HW 2 + HW 3
alenmarz/smart-home-2019 pull request #2
Opened 2019-03-19 20:08 UTC by alenmarz

2019-03-19 21:06 UTC, iagoshkov requested changes
В целом в правильном направлении.
Но есть замечания, много ))
Вы сами делали ДЗ или вам кто-то помогал?

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/alarm/State.java
> +public abstract class State {
Лучше сделать State интерфейсом. И сделать, чтобы Alarm этот интерфейс тоже поддерживал.
Вынести в него методы:
activate
deactivate
alarm (добавить метод, для принудительного перехода в состояние ALARM) - вижу, что есть метод setAlarmState - просто переименуйте его в alarm().

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/alarm/State.java
> +public abstract class State {
Использовать наследование ради одного private поля - это слишком.

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/alarm/Alarm.java
> +public class Alarm {
сделайте чтобы Alarm implements State (State нужно сделать интерфейсом)

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/alarm/handlers/AlarmEventHandler.java
> +            alarm.getState().activate(event.getCode());
Если у вас alarm будет реализовывать интерфейс State (кстати интерфейс лучше назвать тогда как раз просто Alarm, текущий Alarm переименовать, например, в AlarmSystem), то у вас детали реализации alarm (а то, что он сейчас реализован через шаблон state - деталь реализации), не будут протекать в AlarmEventHandler. Вы просто будете работать с сервисом Alarm, а он уже внутри будет устроен на состояниях.
Вызов тогда будет выглядеть так:
`alarm.activate(event.getCode();`
без getState().

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/Room.java
> +        if (action.getActionType() == ActionType.DOOR) {
getActionType - не надо проверять, пускай action сам внутри проверяет, какой объект ему передали и решает - стоит его обрабатывать или нет (по аналогии с eventhandler-ами). Иначе это дополнительное ограничение, которое не дает, например, сделать Action который обрабатывает и двери и свет.
Т.е. метод getActionType не нужен вообще.

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/Room.java
> +                if (name.equals("hall")) {
А зачем break?
Если мы в комнате hall - то достаточно проитерироваться только по одному источнику света? А остальные мы в action не будем передавать? Это почему?

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/action/Action.java
> +    public abstract ActionType getActionType();
Не нужно - я написал выше почему.

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/action/Action.java
> +    protected ActionType actionType;
и поле не нужно

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/action/Action.java
> +        this.event = event;
Зачем в action-е Event?
В абстрактном классе он зачем? У нас могут быть Action-ы, которые вообще никаким образом ни с какими ивентами не связаны. Action - это часть "внутреннего итератора", он с Event-ами вообще не должен никак быть связан.

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/action/Action.java
> +        this.event = event;
Вам может понадобиться Event в какой-то конкретной реализации Action-а, это да.
Но в абстракции Action ничего про event-ы не должно быть.

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/action/Action.java
> +    public Object getEvent() {
Этого тоже не должно быть

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/action/Action.java
> +abstract public class Action<T> {
Сделайте Action лучше интерфейсом.

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/action/LightAction.java
> +            executeHall(roomName);
Все, что связано с Hall - это часть "сценария умного дома", все что не связано с hall - это часть "обновления модели дома".
У вас в одном классе две причины для изменения.
Нарушение SRP.

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/action/LightAction.java
> +        Iterator iterator = new LightIterator(smartHome);
Зачем внешний итератор?
Мы зачем делали Actionable/Action?
Чтобы не делать внешние итераторы.

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/handlers/decorator/AlarmDecorator.java
> +    private void sendSMS() {
Ну это по-хорошему должно быть в отдельном классе.

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/iterator/Iterator.java
> +public interface Iterator {
Это внешний итератор. ДЗ было на внутренний и мы его сделали через Actionable/Action.
А это не нужно. Удалите.

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/iterator/LightIterator.java
> +public class LightIterator implements Iterator {
И это удалить

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/EventHandler.java
> +public abstract class EventHandler {
Зачем abstract class?
Ради одного поля не нужно делать наследование.
Лучше сделать EventHandler интерфейсом.
И убрать из него знание про smartHome.
Реализации - будут знать. Некоторые. А некоторым может и smartHome не нужен будет. Зачем лишние ограничения?

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/SmartHome.java
> +        for (Room room: rooms) {
Здесь можно добавить
`action.execute(this)`

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/alarm/ActivatedState.java
> +        return type;
Здесь можно просто сделать return StateType.ACTIVATED. 
Он же никогда не меняется, зачем поле.

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/alarm/State.java
> +public abstract class State {
getType наверно тоже можно в интерфейсе оставить, т.к. он нужен, чтобы проверять в каком состоянии находится сигнализация.

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/action/LightAction.java
> +    private enum RoomType {
Вот это тоже все знания о сценарии входной двери. SRP нарушается, см. ниже комментарий

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/action/LightAction.java
> +            executeHall(roomName);
Собственно это нарушение SRP можно проследить в наличии двух приватных методов, никак не связанных друг с другом: executeOrdinary и executeHall.
У них практически нулевой cohesion.
Они не используют никакие общие поля, они не связаны одной задачей. Их нужно разнести по разным классам, прямо напрашиваются.

2019-03-19 21:06 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/handlers/LightEventHandler.java
> +public class LightEventHandler extends EventHandler {
уже писал, что лучше обойтись без наследования, сделать EventHandler интефейсом

2019-03-19 21:06 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/handlers/decorator/AlarmDecorator.java
> +        switch (wrappee.getSmartHome().getAlarm().getState().getType()) {
Здесь проще сделать по-другому - AlarmDecorator работает с сигнализацией - она постоянно ему нужна. Логично сделать ее полем и передавать в конструкторе.
Тогда не надо будет вот этого: wrappee.getSmartHome().getAlarm().
Просто обращение к полю:
`alarm.getType()`

2019-03-19 21:06 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/handlers/decorator/AlarmDecorator.java
> +                super.handleEvent(object);
Зачем это? В super.handleEvent никакой логики нет - только будет смущать читателя кода.

2019-03-19 21:06 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/handlers/decorator/AlarmDecorator.java
> +                super.handleEvent(object);
Аааа, понял, там есть логика, вы как раз там делегируете исполнение "завернутому" хэндлеру.
Можно это явно тут сделать.
`wrapee.handleEvent(object)`
и избавиться от промежуточного класса EventHandlerDecorator.

2019-03-23 11:33 UTC, iagoshkov approved these changes
В целом неплохо, по мелочам исправьте.

2019-03-23 11:33 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/action/DoorAction.java
> +    private SensorEvent event;
Вообще лучше чтобы этот Action не знал вообще о существовании такой сущности как Event.
Это лишний coupling.
Все что ему нужно - это Id двери. Пускай его и принимает в конструкторе. Зачем ему весь объект SensorEvent?

2019-03-23 11:33 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/action/LightAction.java
> +        this.event = (SensorEvent) event;
Здесь тоже самое. Достаточно передать id источника света, а не весь SensorEvent.

2019-03-23 11:33 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/handlers/decorator/AlarmDecorator.java
> +                new SMS().send("ALARM!");
А зачем здесь new SMS()?
А если потом решим не SMS?
Есть же интерфейс у вас Notifier.
Пусть принимает в конструкторе его и все.

2019-03-31 22:04 UTC, alenmarz commented on src/main/java/ru/sbt/mipt/oop/home/objects/action/DoorAction.java
> +    private SensorEvent event;
> Все что ему нужно - это Id двери.
Это ведь не так. Помимо id, ему нужно знать еще тип события, который происходит (закрывают дверь или открывают).

2019-03-31 22:05 UTC, alenmarz commented on src/main/java/ru/sbt/mipt/oop/home/objects/action/LightAction.java
> +        this.event = (SensorEvent) event;
Аналогично

2019-04-02 20:30 UTC, iagoshkov requested changes
С адаптером не получилось. Оно просто не будет работать.
Не нужно получать все события, адаптировать их и складывать в коллекцию, а потом всю коллекцию разом обрабатывать. Оно так просто не сработает.

2019-04-02 20:30 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/event/sensor/CCSensorEventsManagerAdapter.java
> +        sensorEventsManager.start();
Вот это место никогда из цикла не выйдет. Библиотека не отдает управление назад.
Нужно адаптировать события по ходу получения, а не получить все события (это вообще как? типа несколько дней ждать, копить события, а потом перед выключением приложения их все адаптировать и обработать?)

2019-04-03 20:49 UTC, alenmarz commented
Добавлена 5я домашка, 4я пока не исправлена.

2019-04-09 19:44 UTC, iagoshkov requested changes
см комментарии

2019-04-09 19:44 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/action/DoorAction.java
> +    private SensorEvent event;
Да. Но не SensorEvent. id двери и что нужно сделать с ней - закрыть или открыть.

2019-04-09 19:44 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/objects/action/DoorAction.java
> +    private SensorEvent event;
Мы в классе разбирали почему это плохо

2019-04-09 19:44 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/remote/RemoteController.java
> +    private Collection<Button> buttons;
Проще сделать
`Map<String, Button> codeToButtonMap;`

2019-04-09 19:44 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/remote/RemoteController.java
> +        buttons.add(new Button(buttonCode, command));
здесь тогда можно будет обойтись одной строчкой:
`buttons.put(buttonCode, new Button(buttonCode,command));`

2019-04-09 19:44 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/remote/RemoteController.java
> +        for (Button button: buttons) {
здесь будет просто
`buttons.get(buttonCode);`

2019-04-09 19:44 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/remote/command/ActivateAlarmCommand.java
> +    public ActivateAlarmCommand(SmartHome smartHome, String securityCode) {
Зачем вы передаете smartHome чтобы потом просто сделать smartHome.getAlarm().
Передавайте в конструкторе сразу alarm

2019-04-09 19:44 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/remote/command/CloseHallDoorCommand.java
> +                    room.execute(new DoorAction(
Вот смотрите, у вас уже команды пульта зависят от SensorEvent.
Хотя это вообще не связанные вещи!
Пульт и команды можно вообще без каких либо событий использовать. Они не должны друг о друге знать.

Это все из-за того, что у вас DoorAction зависит от SensorEvent - это плохая зависимость, она уже через весь код тянется.

2019-04-09 19:44 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/remote/command/SetAlarmModeCommand.java
> +    public SetAlarmModeCommand(SmartHome smartHome) {
передавайте сразу alarm

2019-04-09 19:44 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/remote/command/TurnAllLightOffCommand.java
> +        for (Room room: smartHome.getRooms()) {
Зачем так странно?
Почему не
`smartHome.execute(new LightAction...)`
Мы для этого и делали внутренний итератор, чтобы не нужно было каждый раз делать цикл по всей структуре дома.

2019-04-09 19:44 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/remote/command/TurnAllLightOnCommand.java
> +        for (Room room: smartHome.getRooms()) {
здесь аналогично, внутренний итератор

2019-04-09 19:44 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/home/remote/command/TurnHallLightsOnCommand.java
> +        for (Room room : smartHome.getRooms()) {
Здесь в принципе тоже до уровня комнат можно дойти через внутренний итератор.
А там уже по всем источникам света в комнате обычным циклом.

2019-04-09 19:44 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>      }
А где код который инициализирует пульт, команды и регистрирует пульт?

2019-04-09 19:44 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/tests/rc/ActivateAlarmCommandTest.java
> +        rc.onButtonPressed("A");
А зачем так сложно?
Если вы проверяете работу самой команды - то зачем вам пульт?
И кстати если вы уберете ненужную зависимость этой команды от smartHome то тест упростится.
Вам не нужно загружать состояние дома из файла, оно никак не влияет на тест.
Вам нужно только создать Alarm и настроить его и передать в ActivateAlarmCommand.
Примерно вот так будет выглядеть тест:

`Alarm alarm = new Alarm(new Configuration(securityCode));`
`Command commandToTest = new ActivateAlarmCommand(alarm, securityCode));`
`commandToTest.execute();`
`assert...`

Просто и понятно.

2019-04-09 19:44 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/tests/rc/ActivateAlarmCommandTest.java
> +
А вот теста на сам пульт не хватает.
Чтобы проверить например сценарий, а что происходит, если мы нажимаем кнопку, для которой не зарегистрирована команда.
Или если регистрируем команду на кнопку, на которую уже команда назначена.

2019-04-09 19:44 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/tests/rc/ActivateAlarmCommandTest.java
> +
Но это в отдельном классе конечно нужно сделать

2019-07-15 11:49 UTC, merged